version: '3.8'
services:
  oracle:
    image: 'container-registry.oracle.com/database/enterprise:${ORA_VER}'
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ./db:/scripts   
    environment:
      TZ: ${TZ_IND}
    extra_hosts:
      - "moby:127.0.0.1"
networks:
  default:
    name: my-awesome-app-network
    external: true
